services:
  php:
    image: yiisoftware/yii2-php:8.4-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  database:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"

volumes:
  mariadb_data: